// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAym51GURfaqLWqxrCsIpBC-0iZSrdFbwU',
    appId: '1:727697332450:web:92a2f2114cf220d2e566bb',
    messagingSenderId: '727697332450',
    projectId: 'servili-95a78',
    authDomain: 'servili-95a78.firebaseapp.com',
    storageBucket: 'servili-95a78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9FtCCIu1Pr_attHhcnGnr97fCFj1xG4U',
    appId: '1:727697332450:android:376bf9e75af2b390e566bb',
    messagingSenderId: '727697332450',
    projectId: 'servili-95a78',
    storageBucket: 'servili-95a78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhnQFDg26-aYML_ILL7tY4IjhMIEpjOQ0',
    appId: '1:727697332450:ios:fd9e0c81e87af4c1e566bb',
    messagingSenderId: '727697332450',
    projectId: 'servili-95a78',
    storageBucket: 'servili-95a78.firebasestorage.app',
    iosBundleId: 'com.example.servili',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhnQFDg26-aYML_ILL7tY4IjhMIEpjOQ0',
    appId: '1:727697332450:ios:fd9e0c81e87af4c1e566bb',
    messagingSenderId: '727697332450',
    projectId: 'servili-95a78',
    storageBucket: 'servili-95a78.firebasestorage.app',
    iosBundleId: 'com.example.servili',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAym51GURfaqLWqxrCsIpBC-0iZSrdFbwU',
    appId: '1:727697332450:web:8962063425579e53e566bb',
    messagingSenderId: '727697332450',
    projectId: 'servili-95a78',
    authDomain: 'servili-95a78.firebaseapp.com',
    storageBucket: 'servili-95a78.firebasestorage.app',
  );
}
